In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [13]:
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   target  
0       0  
1       0  
2       0

In [10]:
df['target']=iris.target

In [18]:
df[50:55]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
50       1  
51       1  
52       1  
53       1  
54       1

In [29]:
x=df.drop('target',axis='columns')
y=df['target']
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.svm import SVC
svm=SVC()
from sklearn import tree
tree=tree.DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=10)
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.20)
from sklearn.model_selection import cross_val_score
cvlr=cross_val_score(lr,x,y)
cvsvm=cross_val_score(svm,x,y)
cvtree=cross_val_score(tree,x,y)
cvrf=cross_val_score(rf,x,y)

C:\Users\SMuralidhar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
cvlr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
cvsvm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [24]:
cvtree

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [30]:
cvrf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])